# Generated by Django 4.0.4 on 2022-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channeladmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(blank=True, choices=[('Text', ' Text'), ('Link', 'Link')], max_length=300, null=True),
        ),
    ]
